# Generated by Django 2.1.7 on 2019-07-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='products',
            field=models.ManyToManyField(blank=True, to='home.Product'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='products',
            field=models.ManyToManyField(blank=True, to='home.Product'),
        ),
    ]
