# Generated by Django 2.2.3 on 2019-07-25 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190725_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='products',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Buyer')),
                ('products', models.ManyToManyField(to='home.Product')),
            ],
        ),
    ]
