# Generated by Django 2.2.3 on 2019-07-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190725_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('products', models.ManyToManyField(blank=True, to='home.Product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.ManyToManyField(blank=True, to='home.Quantity'),
        ),
    ]
