# Generated by Django 2.2.3 on 2019-07-25 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190725_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='products',
        ),
        migrations.AddField(
            model_name='quantity',
            name='products',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Product'),
        ),
    ]
